openapi: 3.0.3
info:
  title: LLM API Gateway - 网关代理 API
  description: |
    LLM API Gateway 的核心代理接口，完全兼容 OpenAI API 格式。
    客户端通过添加 `App-Name` header 标识身份，网关自动路由到配置的后端 LLM 服务器。
  version: 1.0.0
  contact:
    name: Vega Team

servers:
  - url: http://localhost:8000
    description: 本地开发环境
  - url: https://gateway.example.com
    description: 生产环境

paths:
  /v1/chat/completions:
    post:
      summary: 聊天补全接口（代理）
      description: |
        代理客户端的聊天补全请求到后端 LLM 服务器。
        请求格式完全兼容 OpenAI Chat Completion API。
      operationId: chatCompletions
      tags:
        - Gateway Proxy
      parameters:
        - name: App-Name
          in: header
          required: true
          description: 客户端应用名称，用于用量统计和身份标识
          schema:
            type: string
            example: "my-chatbot"
            minLength: 1
            maxLength: 100
      requestBody:
        required: true
        description: OpenAI 格式的聊天补全请求
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatCompletionRequest'
            examples:
              gpt4_example:
                summary: GPT-4 请求示例
                value:
                  model: "gpt-4"
                  messages:
                    - role: "user"
                      content: "Hello, how are you?"
                  temperature: 0.7
                  max_tokens: 150
      responses:
        '200':
          description: 成功响应（来自后端 LLM 服务器）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletionResponse'
        '400':
          description: 请求错误（缺少 App-Name header 或请求格式不正确）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                missing_app_name:
                  summary: 缺少 App-Name header
                  value:
                    error:
                      message: "Missing required header: App-Name"
                      type: "invalid_request_error"
                      code: "missing_header"
        '404':
          description: 模型不存在（请求的模型在所有后端服务器中都不可用）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                model_not_found:
                  summary: 模型不存在
                  value:
                    error:
                      message: "Model 'gpt-5' is not available"
                      type: "invalid_request_error"
                      code: "model_not_found"
        '502':
          description: 后端服务器不可用
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                backend_unavailable:
                  summary: 后端服务器错误
                  value:
                    error:
                      message: "Backend server is unavailable"
                      type: "service_unavailable"
                      code: "backend_error"
        '503':
          description: 队列已满（被 FIFO 驱逐）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                queue_full:
                  summary: 队列已满
                  value:
                    error:
                      message: "Request queue is full, your request was evicted"
                      type: "rate_limit_error"
                      code: "queue_full"
        '504':
          description: 排队超时
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                queue_timeout:
                  summary: 排队超时
                  value:
                    error:
                      message: "Request timed out while waiting in queue"
                      type: "timeout_error"
                      code: "queue_timeout"

  /health:
    get:
      summary: 健康检查
      description: 检查网关服务是否正常运行
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  timestamp:
                    type: string
                    format: date-time

components:
  schemas:
    ChatCompletionRequest:
      type: object
      required:
        - model
        - messages
      properties:
        model:
          type: string
          description: 要使用的模型名称
          example: "gpt-4"
        messages:
          type: array
          description: 聊天消息列表
          items:
            $ref: '#/components/schemas/ChatMessage'
        temperature:
          type: number
          format: float
          description: 采样温度 (0.0 - 2.0)
          default: 1.0
          minimum: 0.0
          maximum: 2.0
        max_tokens:
          type: integer
          description: 生成的最大 token 数
          example: 150
        stream:
          type: boolean
          description: 是否启用流式响应
          default: false

    ChatMessage:
      type: object
      required:
        - role
        - content
      properties:
        role:
          type: string
          enum: [system, user, assistant]
          description: 消息角色
        content:
          type: string
          description: 消息内容

    ChatCompletionResponse:
      type: object
      properties:
        id:
          type: string
          description: 响应 ID
          example: "chatcmpl-123"
        object:
          type: string
          example: "chat.completion"
        created:
          type: integer
          description: Unix 时间戳
          example: 1699999999
        model:
          type: string
          description: 使用的模型
          example: "gpt-4"
        choices:
          type: array
          items:
            $ref: '#/components/schemas/ChatChoice'
        usage:
          $ref: '#/components/schemas/Usage'

    ChatChoice:
      type: object
      properties:
        index:
          type: integer
          example: 0
        message:
          $ref: '#/components/schemas/ChatMessage'
        finish_reason:
          type: string
          enum: [stop, length, content_filter]

    Usage:
      type: object
      properties:
        prompt_tokens:
          type: integer
          description: 提示词 token 数
          example: 10
        completion_tokens:
          type: integer
          description: 生成内容 token 数
          example: 50
        total_tokens:
          type: integer
          description: 总 token 数
          example: 60

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            message:
              type: string
              description: 错误信息
            type:
              type: string
              description: 错误类型
              enum:
                - invalid_request_error
                - rate_limit_error
                - service_unavailable
                - timeout_error
            code:
              type: string
              description: 错误代码
              enum:
                - missing_header
                - model_not_found
                - backend_error
                - queue_full
                - queue_timeout
